version: '3.8'

services:
  app:
    image: proxy-server
    container_name: proxy-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
