version: '3.8'

services:
  app:
    image: todo-list
    container_name: todo-list
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
