basePath: /
definitions:
  models.Request:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  models.Response:
    properties:
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      id:
        type: string
      length:
        type: integer
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server to proxy HTTP requests.
  title: HTTP Proxy Server API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      description: Proxies an HTTP request to a specified URL.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Proxy HTTP request
  /health:
    get:
      consumes:
      - application/json
      description: This endpoint checks the health of the server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - health
swagger: "2.0"
